---
- name: Create deploy_user and add to groups
  ansible.builtin.user:
    name: "{{ deploy_username }}"
    shell: /bin/bash
    groups: 
      - docker
      - www-data
    append: yes
    password: "*"

- name: Install authorized_key for current environment
  ansible.builtin.authorized_key:
    user: "{{ deploy_username }}"
    state: present
    key: "{{ hostvars['localhost']['deploy_pub_key_' + env_label] }}"

- name: Create project directory
  ansible.builtin.file:
    path: "/home/{{ deploy_username }}/app"
    state: directory
    owner: "{{ deploy_username }}"
    group: docker
    mode: '0755'
