#SPDX-License-Identifier: MIT-0
---
# tasks file for insecure-registries
- name: Configure insecure registry for Docker
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: '0644'
  notify: Restart docker
